### ISSUE TITLE
multi-line prompt is combined

### ISSUE THREAD

**Issue by feigaoxyz** [acomagu/fish-async-prompt#19]
If the prompt is multi-line, the plugin combined all lines into one line.

For example, set prompt to `Simple Pythonista` from `fish_config`, the correct output is

```
user at hostname in ~/.c/f/conf.d
↪
```

If we enabled the async plugin, the output is crashed into one line:

```
user at hostname in ~/.c/f/conf.d ↪
```

----

Guess for most user with 2-line prompt, the first line is heavy one with lots of information and computing-intensive, while the second line is usually a short symbol.

Just want to check if it is possible to display second line quickly, while waiting for the first line being computed async.

**Comment by acomagu** [comment]
Fixed by #21. Thanks!!
