### ISSUE TITLE
Variable name '__async_prompt_fish_prompt_text_%self' is not valid

### ISSUE THREAD

**Issue by c02y** [acomagu/fish-async-prompt#2]
set: Variable name '__async_prompt_fish_prompt_text_%self' is not valid. See `help identifiers`.
Standard input (line 16):
    set -U __async_prompt_fish_prompt_text_%self (fish_prompt)
    ^
kill: failed to parse argument: '%self'
set: Variable name '__async_prompt_fish_right_prompt_text_%self' is not valid. See `help identifiers`.
Standard input (line 16):
    set -U __async_prompt_fish_right_prompt_text_%self (fish_right_prompt)
    ^
kill: failed to parse argument: '%self'

FYI
fish, version 2.7.1-1368-gb39651f

**Comment by acomagu** [comment]
I couldn't reproduce...
Is it happens every time on showing prompt?

**Comment by acomagu** [comment]
OK, I could reproduced. I'll investigate.
Thank you for telling the detail!

**Comment by acomagu** [comment]
Fixed at 0d63f8c
Thanks!

**Comment by c02y** [comment]
And if I use the following command to clean all my fish configuration:

      sh -c 'env HOME=$(mktemp -d) fish'

which is suggested by official new issue page of fish-shell github page and then

      source /path/to/__async_prompt.fish

It seems OK, but if I 

    source /path/to/__async_prompt.fish

in my config.fish and use normal fish not the `sh -c 'env HOME=$(mktemp -d) fish'` one, the problem I mentioned:

    test returned eval errors:
        invalid number ''

is still there.

**Comment by c02y** [comment]
Any updates？

**Comment by acomagu** [comment]
It must be fixed currently. I'm sorry for long blank.
