### ISSUE TITLE
Fish gives errors when trying to inherit variables

### ISSUE THREAD

**Issue by comfortablynick** [acomagu/fish-async-prompt#26]
I am running fish 3.0.2 on Arch with the bobthefish theme. When I add your plugin, everything works fine but none of my bobthefish options is preserved. If I `set -g async_prompt_inherit_variables 'all'`, I get the following errors on every prompt:

```
set: Tried to change the read-only variable “fish_pid”                                                                           
set: Tried to change the read-only variable “hostname”
set: Tried to change the read-only variable “version”
set: Tried to change the read-only variable “fish_pid”
set: Tried to change the read-only variable “hostname”
set: Tried to change the read-only variable “version”
```

Is there a way to fix this?

**Comment by acomagu** [comment]
I fixed these error. If you still have problems, please reopen.
Thank you for reporting!
