### ISSUE TITLE
Old prompt is not cleared when new prompt is shorter

### ISSUE THREAD

**Issue by evanrelf** [acomagu/fish-async-prompt#28]
My prompt displays Git dirty status and branch name, which takes a long time to run in my company's Git monorepo. `fish-async-prompt` gets rid of the lag I had before when waiting for Git to return so Fish could draw my prompt, but now there's a new problem.

```
~/Projects/company-name/the-monorepo [master]
λ cd ..

~/Projects/company-name the-monorepo [master]
λ echo foo bar
foo bar

~/Projects/company-name
λ
```

When my prompt becomes shorter, for example by changing to a parent directory, the old prompt doesn't get cleared completely. Only the parts that "overlap" get updated.

**Comment by acomagu** [comment]
@evanrelf Could you shere your prompt function code or config.fish?

**Comment by evanrelf** [comment]
Sure. [Here's my `fish_prompt`](https://github.com/evanrelf/dotfiles/blob/12a3140049023582718a4f0c1a6bb4ef9c7bddd5/fish/.config/fish/modules/appearance.fish#L58-L134)

**Comment by acomagu** [comment]
Hmm, I cannot reproduce even if with your prompt function code.

What Fish version are you using?

and if possible, could you create reproduction procedure in the fresh environment, created by `sh -c 'env -i TERM=$TERM HOME=$(mktemp -d) fish'`?

**Comment by robbplo** [comment]
I've noticed this as well using https://github.com/matchai/spacefish

**Comment by evanrelf** [comment]
Sorry for the late reply @acomagu. I'm using fish 3.0.2. I tried to reproduce the problem I had in a fresh environment, but I ended up running into other issues and I didn't have time to fix them.

**Comment by acomagu** [comment]
Thanks! I reproduced with matchai/spacefish.
I'll see it in this weekend.

**Comment by acomagu** [comment]
It's solved if this issue is fixed: https://github.com/fish-shell/fish-shell/issues/6532

**Comment by acomagu** [comment]
Today I rewrite the almost whole this plugin, and this issue seems no longer reproduced on the latest version(v1.1.0). Can anyone tries?

**Comment by evanrelf** [comment]
@acomagu I installed the latest version of the plugin, and I no longer experience this issue 🎉

**Comment by acomagu** [comment]
@evanrelf Thank you!! I close here.
