### ISSUE TITLE
`sh <defunct>` processes are spawned.

### ISSUE THREAD

**Issue by acomagu** [acomagu/fish-async-prompt#30]
```
$ uname -a
Linux acm-manjaro 4.19.112-1-MANJARO #1 SMP Fri Mar 20 20:32:56 UTC 2020 x86_64 GNU/Linux
$ fish --version
fish, version 3.1.0
```

**Comment by acomagu** [comment]
`function ... --on-process-exit PID` seems not to be fired. `--on-job-exit` also doesn't work.

**Comment by acomagu** [comment]
#31

**Comment by acomagu** [comment]
Follow https://github.com/fish-shell/fish-shell/issues/6828

**Comment by NovaDev94** [comment]
I noticed it while working on my own async git prompt too, `--on-process-exit PID` and `--on-job-exit` doesn't work for nested functions (declared locally) on Fish 3.1.0

**Comment by acomagu** [comment]
@NovaDev94 Thank you for the information. Hmm, that's a bit disappointing. I have no idea to do without function nesting.

**Comment by davidcelis** [comment]
is there any update on trying to get this to work with Fish 3.1.x?

**Comment by acomagu** [comment]
@davidcelis In my environment, it works on Fish 3.1.2. Do you have any trouble?

**Comment by acomagu** [comment]
I updated the issue title refrecting the current status. Now it works on Fish 3.1.x(if not, create new issue). I'm sorry if it made confusion.

**Comment by acomagu** [comment]
Fixed by https://github.com/fish-shell/fish-shell/pull/6861.
