### ISSUE TITLE
prompt does not render in fish 3.1 (dev or upcoming 3.2)

### ISSUE THREAD

**Issue by miki725** [acomagu/fish-async-prompt#40]
Just installed fish 3.1 dev from git or upcoming 3.2 and noticed that async prompt does not render automatically when starting fish:

```
$ fish
Welcome to fish, the friendly interactive shell
```

the prompt will not appear until pressing `Enter`. Probably some incompatibility with latest fish.

```
$ fish --version
fish, version 3.1.2-1616-g3e3a42c12
```

**Comment by jorgebucaran** [comment]
@miki725 You must mean 3.1.

**Comment by acomagu** [comment]
@miki725 @jorgebucaran Must be fixed at 3564a29. Could you try it?

**Comment by miki725** [comment]
seems to be working. thanks for the quick fix!

**Comment by miki725** [comment]
or broke on mac though:

```
<W> fish: An error occurred while redirecting file '/run/user/501/fish-async-prompt/21225_fish_prompt'
open: No such file or directory
```

**Comment by acomagu** [comment]
@miki725 Thank you for trying. I changed the tmpdir to `/tmp` instead of `/run` at 358dda6. Please try it again? :sweat_drops:

**Comment by miki725** [comment]
seems to be working fine. thanks

**Comment by acomagu** [comment]
@miki725 Thank you!!
