### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by andreiborisov** [acomagu/fish-async-prompt#43]
Would it be possible to print some sort of loading indicator instead of the previous prompt before printing a new one?

**Comment by acomagu** [comment]
Like this?
https://user-images.githubusercontent.com/1362750/102706844-bf9c6900-42d8-11eb-9858-fb73cc380071.mp4

**Comment by andreiborisov** [comment]
Yes🙌🏻

**Comment by andreiborisov** [comment]
It would be even cooler to have some simple animation, but I assume it would be a nightmare to implement if even possible.

**Comment by acomagu** [comment]
Yes I guess implementing animation will be hard because extra processes must be spawned. But I may try because I think it's cool feature also.

But for now, I'll implement the non-animated loading indicator. Thank you for good suggestion!

**Comment by andreiborisov** [comment]
Thank you for an awesome tool you made🙏

**Comment by andreiborisov** [comment]
Do you mind making the loading indicator string customizable via a variable?

**Comment by acomagu** [comment]
Yeah, I'll make it customizable by defining a function.

```
function fish_right_prompt_loading_indicator
    echo (set_color '#aaa')' … '(set_color normal)
end
```

**Comment by acomagu** [comment]
Finally it's supported at 01741b0! Thank you!
