### ISSUE TITLE
How to test this?

### ISSUE THREAD

**Issue by edouard-lopez** [acomagu/fish-async-prompt#44]
How I can create a situation where fish-async-prompt is triggered, so I see the content of my fish_right_prompt_loading_indicator?

I tried something like

	  ❯ function fish_right_prompt_loading_indicator
	            echo (set_color '#aaa')' … '(set_color normal)
	    end
	  ❯ sleep 6s

But to no avail. Is there other thing I need to set up?

**Comment by acomagu** [comment]
@edouard-lopez The loading indicator is shown when the prompt function takes time. So how about inserting `sleep` command to your `fish_right_prompt` function, like

```fish
function fish_right_prompt
    sleep 6
    ...
end
```

?
