### ISSUE TITLE
Not working with keybindings for prevd/nextd

### ISSUE THREAD

**Issue by mickimnet** [acomagu/fish-async-prompt#45]
Hello everybody,

_Fish Shell_ has a very nice feature for the keys <kbd><kbd>Alt</kbd> + <kbd>←</kbd></kbd> and <kbd><kbd>Alt</kbd> + <kbd>→</kbd></kbd>, which are bound to the internal functions `prevd-or-backward-word` and `nextd-or-forward-word`.

Those functions are active while on the command line only if at the beginning of the line **and** the command line is empty, the function `prevd` or `nextd` is called. Those functions change to the previous or next directory in the directory stack. That doesn't issue a new command line, but the current working directory is changed.

Without `fish-async-prompt` _Fish Shell_ does change both prompts (and the terminal title, if enabled) and no line feed is issued.

With `fish-async-prompt` the content of both prompts is **not** changed, but the terminal title (if enabled) and therefore the current working directory is truly changed.

Thanks & take care
Mick

**Comment by acomagu** [comment]
Thanks for the reporting. I didn't know that feature.

The root cause is same as #34. fish-async-prompt has no way to detect repainting the prompt without `fish_prompt` event currently.

I'll managed to do it. Thank you.

**Comment by mickimnet** [comment]
You're welcome. I was guessing, that it may have something to do with #34, and I wanted to explicitly check for the keybinding function.

Take care
