### ISSUE TITLE
Is it possible to support spinner?

### ISSUE THREAD

**Issue by edouard-lopez** [acomagu/fish-async-prompt#46]
I created a repo with some [spinner presets](https://github.com/edouard-lopez/fish-async-prompt-spinner) but can't get them to behave in the same way as when called directly.
Indeed only the last character is visible.

Is the feature possible?

**Comment by acomagu** [comment]
The loading indicator function is executed at the foreground process. It means that the function is not asynchronous. So loading indicators can't be updated/animated, currently.

To implement spinner or something other animated indicator, we need to spawn another process to update it asynchronously. I feel it's too complicated/troublesome compared to the benefits. I'm sorry.

(But I'm glad if I can see fork/pull supporting it. I could accept it if it is easier than I'm considering)
