### ISSUE TITLE
$pipestatus not passed to wrapped prompt

### ISSUE THREAD

**Issue by neersighted** [acomagu/fish-async-prompt#55]
It looks like the `$pipestatus` variable is not passed through by default, and the naive solution of setting `$async_prompt_inherit_variables` does not work as it's read-only and needs to be special-cased like `$status`.

**Comment by acomagu** [comment]
working on this. please wait for days

**Comment by acomagu** [comment]
@neersighted I believe #57 resolves this issue! If the fix is problematic, please create new issue. Thank you!
