### ISSUE TITLE
Invalid Index value when installing using fisher

### ISSUE THREAD

**Issue by aniketgm** [acomagu/fish-async-prompt#60]
### Error
I'm getting the following error when installing using fisher.
```
[17:47] λ ~ ›› fisher install acomagu/fish-async-prompt
fisher install version 4.3.5
Fetching https://api.github.com/repos/acomagu/fish-async-prompt/tarball/HEAD
Installing acomagu/fish-async-prompt
           /home/aniketgm/.config/fish/conf.d/__async_prompt.fish
Updated 1 plugin/s
fish: Invalid index value
            set -f _pipestatus $line[2..]
                                        ^
fish: Invalid index value
            set -f _pipestatus $line[2..]
                                        ^
[17:49] λ ~ ››
```
### System Configuration
Result of `uname -a`
> Linux LAPTOP-HP 5.10.16.3-microsoft-standard-WSL2 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by acomagu** [comment]
Does upgrading Fish fix?

**Comment by aniketgm** [comment]
> Does upgrading Fish fix?
Yup. worked after upgrading. I'm using Ubuntu 20.04 and "apt install fish" gives 3.1.0 as latest.
I had to install from source.
