### ISSUE TITLE
set: Tried to change the read-only variable 'status_generation'

### ISSUE THREAD

**Issue by jvolden** [acomagu/fish-async-prompt#63]
Setting `set -U async_prompt_inherit_variables all` produces the error in the title.

```fish
~ ❱ fish --version
fish, version 3.5.0
```

Plugins:

```fish
~ ❱ fisher list
jorgebucaran/fisher
gazorby/fish-exa
laughedelic/fish_logo
jorgebucaran/nvm.fish
jethrokuan/z
jorgebucaran/autopair.fish
jorgebucaran/hydro
acomagu/fish-async-prompt
```

There may be a better way but I manually excluded that variable.

```
 144   │             for item in (set -ng)
 145   │                 if test "$item" != "status_generation"
 146   │                     echo $item
 147   │                 end
 148   │             end
```

Side note: I'm setting to `all` because hydro prompt does not show up with default values. I didn't take the time to see what variable fixes it, so I added them all.

**Comment by acomagu** [comment]
@jvolden Fixed. Thank you!

**Comment by patricklewis** [comment]
I am on the latest commit (`fcc8c25`) but still seeing the status_generation error when I open a new shell

<img width="537" alt="image" src="https://user-images.githubusercontent.com/17719/221376982-d637047f-351a-424e-81ba-1dc8b65b400f.png">

**Comment by acomagu** [comment]
@patricklewis I'm sorry, I fixed the latest commit. Would you try it again after pull it? Thank you!

**Comment by patricklewis** [comment]
@acomagu I no longer get a "status_generation" error after that commit, thank you!
