### ISSUE TITLE
Error when closing terminal too soon

### ISSUE THREAD

**Issue by Susensio** [acomagu/fish-async-prompt#64]
Sometimes on closing the terminal, I get an error because fish-async-prompt is running in the background.
It happens when I close it fast. Is there someway to avoid this?

![Screenshot from 2023-01-17 18-24-34](https://user-images.githubusercontent.com/11474625/212969308-6c6bc820-4edf-40b1-9bef-75ccd15a07d3.png)

**Comment by Susensio** [comment]
This is happening only on ^D, which sends and EOF to the terminal and does not SIGINT the background process...

**Comment by amok** [comment]
Another way to re-produce this is to open a sub-shell and close it quickly.
Here is a demo of this (right after starting sub-shell `Ctrl+D` is pressed)


https://user-images.githubusercontent.com/1369559/216029662-7bcd62ab-a628-4221-979d-94896333b16d.mp4

It looks like these lines
https://github.com/acomagu/fish-async-prompt/blob/b866f232a4a5ded7e16cda648648c43925c01ba0/conf.d/__async_prompt.fish#L133-L137

trigger repaint on a terminated shell, so `kill` shows an error message

https://github.com/acomagu/fish-async-prompt/blob/b866f232a4a5ded7e16cda648648c43925c01ba0/conf.d/__async_prompt.fish#L55-L57

**Comment by acomagu** [comment]
@Susensio What is your Terminal Emulator?(the confirmation message is displayed by your terminal emulator, right?)

[The background fish process is disowned](https://github.com/acomagu/fish-async-prompt/blob/b866f232a4a5ded7e16cda648648c43925c01ba0/conf.d/__async_prompt.fish#L138) every time so Fish shell doesn't own the process as job.

**Comment by Susensio** [comment]
There is a bug in Gnome Console that causes this. https://gitlab.gnome.org/GNOME/console/-/issues/127

I switched my terminal emulator and its working fine now.

**Comment by acomagu** [comment]
@Susensio I see, thank you!
