### ISSUE TITLE
Switching to normal mode (vi keys) modifies $status and $pipestatus

### ISSUE THREAD

**Issue by dnnr** [acomagu/fish-async-prompt#69]
When using fish's default prompt and vi-like keybindings, pressing Escape to enter the vi normal mode appears to inadvertently set `$status` and $pipestatus to `1`.

This can be observed by the red `[1]` marker that gets added to the prompt right after pressing Escape.

Switching back to insert mode sets `$status` and `$pipestatus` back to their original values.

**Comment by acomagu** [comment]
@dnnr Hi, sorry for long inconvenience. I think that issue is resolved by 23e416f. Could you confirm it?

**Comment by dnnr** [comment]
No problem at all, thanks for working on it! Sadly, I can't confirm that the change fixes the issue. Instead of only getting the failure marker when switching to normal mode, it's permanently there now.

I was also able to reproduce the problem in a fresh debian:unstable docker container running fish 3.7.0. Let me know if there's anything else I can do to help zero in on the issue.
