### ISSUE TITLE
the async-prompt fish script will make fish prompt hang for v3.0

### ISSUE THREAD

**Issue by c02y** [acomagu/fish-async-prompt#7]
I've tried to comment/uncomment piece by piece in my config.fish, and it turns out that the async prompt fish script file made fish prompt hang. No other info, so if you need anything, please let me know.

**Comment by acomagu** [comment]
My environment, it is working on fish 3.0.2.

**Comment by acomagu** [comment]
I'm really sorry for my late reply.
Could you try again on newer version of fish, maybe?
I don't know it's a related thing, but on my environment the master version of fish is hung(even if without async-prompt). The release version(3.0.2) is work.

**Comment by c02y** [comment]
Yeah, it works for v3.0.2 again.

Have you ever considered to write a pull request to [fish-shell repo](https://github.com/fish-shell/fish-shell) and let them merge this feature into fish-shell?

**Comment by acomagu** [comment]
Thank you.
Hmm... Probably I won't create PR for fish core repository because this plugin works enough for me so I don't have motivation. Additionally I'm not familiar with such big C++ project. :thinking:

**Comment by acomagu** [comment]
But it's still nice feature, because Fish plugin often break. It's hard to maintain code to work on both of Linux and macOS.
