### ISSUE TITLE
Prompt not updating

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [acomagu/fish-async-prompt#70]
**Issue Description:**
When utilizing the `zi` (zoxide interactive) command as a keybinding, the prompt does not update or repaint to reflect the changes in the current directory. 

**Steps to Reproduce:**
1. Install [zoxide](https://github.com/ajeetdsouza/zoxide) and set it up with fish.
2. Bind `zi` to a key similar to: `bind \e\cz "__zoxide_zi; commandline -f repaint"`
3. Navigate to a directory using the keybinding.
4. Observe that the prompt does not update to show the new directory.

**Expected Behavior:**
The prompt should automatically update to reflect the current working directory after using the keybinding.

**Comment by ilyagr** [comment]
Did you find a fix? I have a similar problem with #77
