### ISSUE TITLE
Disable for Warp

### ISSUE THREAD

**Issue by andreiborisov** [acomagu/fish-async-prompt#72]
Warp doesn't support prompt redrawing by fish; instead, it takes complete control of prompt rendering.

Is it possible to turn off the plugin only for Warp by configuring or updating it?

We can test for Warp runtime by checking `$TERM_PROGRAM == "WarpTerminal"`.

**Comment by acomagu** [comment]
@andreiborisov Hi, added `async_prompt_enable` flag. Please refer the last of README.
