### ISSUE TITLE
Compatibility with Starship

### ISSUE THREAD

**Issue by injust** [acomagu/fish-async-prompt#82]
Title. Just wanted a definitive answer, as I've seen people write that `fish-async-prompt` only works with native `fish` prompt. But I also see people's dotfiles using this with Starship...

**Comment by eljamm** [comment]
> Title. Just wanted a definitive answer, as I've seen people write that `fish-async-prompt` only works with native `fish` prompt. But I also see people's dotfiles using this with Starship...

Don't know where this was said, but it seems that `fish-async-prompt` works fine with `starship`.
You just need to have `starship init fish | source` at the end of your config file as per the [starship installation](https://starship.rs/guide/#%F0%9F%9A%80-installation) guide.

**Comment by injust** [comment]
Thanks for the answer. I played around with `fish-async-prompt` and it seems to work with Starship.

The one big caveat I've found (originally called out in https://github.com/acomagu/fish-async-prompt/issues/74) is that you must `starship init fish | source`, even in non-interactive shells.

Going to close this as my question's been answered. (This should've been a discussion, sorry!)
