### ISSUE TITLE
not compatible with tide prompt

### ISSUE THREAD

**Issue by daUnknownCoder** [acomagu/fish-async-prompt#85]
im having issues with tide prompt which entirely doesnt show up when i install this plugin, while also being an async plugin

**Comment by bitconym** [comment]
Tide prompt is already async https://github.com/IlanCosman/tide?tab=readme-ov-file#asynchronous-rendering

**Comment by daUnknownCoder** [comment]
ohh right, i thought it asyncs all plugins installed in fish shell, my bad:
![image](https://github.com/user-attachments/assets/9b8a7c3c-3dac-4b90-b89a-c7da10347b88)
